const USER_SIGNIN = 'USER_SIGNIN';
const USER_SIGNOUT = 'USER_SIGNOUT';
const ADD_FAVOURITE = 'ADD_FAVOURITE';
const REMOVE_FAVOURITE = 'REMOVE_FAVOURITE';
export {
  USER_SIGNIN,
  USER_SIGNOUT,
  ADD_FAVOURITE,
  REMOVE_FAVOURITE
};
